# Generated by Django 2.2.1 on 2019-06-27 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='', max_length=100)),
                ('Birth_date', models.DateField()),
                ('gender', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ('author_name',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(default='', max_length=100)),
                ('plot', models.CharField(default='', max_length=1000)),
                ('book_type', models.CharField(default='', max_length=100)),
                ('author_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='book_id', to='Application.Author')),
            ],
            options={
                'ordering': ('book_name',),
            },
        ),
    ]
