# Generated by Django 2.2.1 on 2019-07-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='resources/%Y/%m/'),
        ),
    ]
